version: '2'

volumes:
  spark-sql-data:
    name: spark-sql-data

services:

  broadsea-spark-sql:
    build: .
    image: ohdsi/broadsea-spark-sql:1.0.2
    container_name: broadsea-spark-sql
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "10000:10000"
    volumes:
     - spark-sql-data:/spark-home
